#!/usr/bin/env bash
# Packagers: you need to replace this script with something, that will work for your distro.
# Otherwise, just don't install this script. The tray system update notifier won't show up,
# as well as related nwg-shell-config options.

if [ "$2" = "-yay" ]; then
    yay -Syu;
else
    baph -u;
fi
echo "$1"; read -r;
