#!/usr/bin/env bash
# Packagers: you need to replace this script with something, that will work for your distro.
# Otherwise, just don't install this script. The tray system update notifier won't show up,
# as well as related nwg-shell-config options.

case "$2" in
    "-pacman") sudo pacman -Syu ;;
    "-yay") yay -Syu ;;
    "-baph") baph -u ;;
    "-scratch") scratch sysup ;;
esac
echo "$1"; read -r;
